In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import fetch_california_housing
import joblib

In [68]:
df = fetch_california_housing()
df

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [69]:
x = pd.DataFrame(df.data, columns=df.feature_names)
y = df.target

In [70]:
x
# print(y)

MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0      8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1      8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2      7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3      5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4      3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25
...       ...       ...       ...  ...       ...       ...        ...
20635  1.5603      25.0  5.045455  ...  2.560606     39.48    -121.09
20636  2.5568      18.0  6.114035  ...  3.122807     39.49    -121.21
20637  1.7000      17.0  5.205543  ...  2.325635     39.43    -121.22
20638  1.8672      18.0  5.329513  ...  2.123209     39.43    -121.32
20639  2.3886      16.0  5.254717  ...  2.616981     39.37    -121.24

[20640 rows x 8 columns]

In [71]:
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [74]:
from sklearn.tree import DecisionTreeRegressor

In [75]:
regressor = DecisionTreeRegressor()

In [76]:
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [77]:
y_pred = regressor.predict(x_test)
y_pred

array([0.425  , 1.203  , 5.00001, ..., 5.00001, 0.656  , 2.172  ])

In [78]:
from sklearn.metrics import  r2_score

In [79]:
score = r2_score(y_pred, y_test)
score

0.6218864826565031

Hyperparameter Tunning

In [80]:
parameters = {
  'criterion': ['squared_error', 'friedman_mse', 'absolute_error'],
  'splitter': ['best', 'random'],
  'max_depth': [1,2,3,4,5,6,7,8,9,10,11,12],
  'max_features': ['auto', 'sqrt', 'log2']
}
regressor = DecisionTreeRegressor()

In [81]:
from sklearn.model_selection import GridSearchCV

In [82]:
regressorcv = GridSearchCV(regressor, param_grid=parameters, cv=5, scoring='neg_mean_squared_error')

In [83]:
regressorcv.fit(x_train,y_train)

c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
360 fits failed out of a total of 1080.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
360 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1356, in wrapper
    estimator._validate_params()
  File "c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared_error')

In [84]:
regressorcv.best_params_

{'criterion': 'friedman_mse',
 'max_depth': 11,
 'max_features': 'log2',
 'splitter': 'best'}

In [85]:
y_pred = regressorcv.predict(x_test)

In [86]:
y_pred

array([0.56686957, 1.4225    , 4.95600667, ..., 4.97491869, 0.87017935,
       1.68452558])

In [87]:
r2_score(y_pred, y_test)

0.5758718779645835