In [2]:
import numpy as np

In [4]:
#creating a 3*3 random numpy array
arr = np.random.randint(1, 101, size=(3, 3))
print(arr)
print(arr.shape)

[[100  87  10]
 [ 71  43  13]
 [ 77  76  60]]
(3, 3)


In [15]:
#coverting sane array in float array
arr.astype('float')

array([[100.,  87.,  10.],
       [ 71.,  43.,  13.],
       [ 77.,  76.,  60.]])

In [23]:
#flattern and fancy indexing
flat = arr.flatten()
index = flat[[4,3,5]]
print(index)

[43 71 13]


In [28]:
#creating 1d array to 3*3 array
flat.reshape(3,3)

array([[100,  87,  10],
       [ 71,  43,  13],
       [ 77,  76,  60]], dtype=int32)

In [30]:
#applying boolean masking to array
flat[flat>50]

array([100,  87,  71,  77,  76,  60], dtype=int32)