In [7]:
import numpy as np

Vectorization

In [5]:
arr = np.array([9,6,8,3,2])
result = arr ** 2
result

array([81, 36, 64,  9,  4])

Broadcasting - No extra memory is used


In [11]:
broadcast = result + 10
broadcast

array([91, 46, 74, 19, 14])

Normalizing data using Broadcasting

In [15]:
mean = broadcast.mean(axis=0)
std = broadcast.std(axis=0)
normalized_data = (broadcast-mean)/std
print(normalized_data)

[ 1.4031166  -0.09309778  0.83788005 -0.99082641 -1.15707245]
